---
version: '3'
services:
  postgres:
    image: postgres:15.3
    container_name: snap-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty12345
      POSTGRES_DB: postgres