graceful_timeout: 30s

invest:
  AccountID: ""
  APIToken: "t.-g2iCbUiAcSEJO4gJHzNy-EffcmKdigW87r6opyYxXL9esWnHEPzayb7_iDlaY6CwrMSiE1GEPC-__484ZDuoQ"
  EndPoint: sandbox-invest-public-api.tinkoff.ru:443
  AppName: snap-bot
  DisableResourceExhaustedRetry: true
  DisableAllRetry: true
  MaxRetries: 3

httpserver:
  listen: :8080
  read_timeout: 60s
  write_timeout: 60s

grpc:
  port: 44044
  timeout: 10h

