graceful_timeout: 30s

invest:
  AccountID: ""
  APIToken: ""
  EndPoint: sandbox-invest-public-api.tinkoff.ru:443
  AppName: snap-bot
  DisableResourceExhaustedRetry: true
  DisableAllRetry: true
  MaxRetries: 3

httpserver:
  listen: :8081
  read_timeout: 60s
  write_timeout: 60s

grpc:
  port: 44044
  timeout: 10h

